name: Publish Results from Pull Requests

on:
  workflow_run:
    workflows: [Pull Request Build]
    types:
      - completed

permissions:
  checks: write
  statuses: write

jobs:
  publish:
    # only run in the official pmd repo, where we have access to the secrets
    if: github.repository == 'pmd/pmd'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - name: Download PR info
        uses: actions/download-artifact@v4
        with:
          name: pr-info
          run-id: ${{ github.event.workflow_run.id }}
      - run: |
          PR_NUMBER="$(cat ./PR_NUMBER)"
          echo "PR_NUMBER=${PR_NUMBER}" >> "$GITHUB_ENV"
          PR_SHA="$(cat ./PR_SHA)"
          echo "PR_SHA=${PR_SHA}" >> "$GITHUB_ENV"
      - name: Download docs-artifact
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          mkdir docs-artifact
          cd docs-artifact
          gh run download "${RUN_ID}" --repo pmd/pmd --name docs-artifact
      - name: Upload docs-artifact to s3://pmd-pull-requests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_PMD_PULL_REQUESTS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_PMD_PULL_REQUESTS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
        run: |
          aws s3 sync docs-artifact "s3://pmd-pull-requests/pr-${PR_NUMBER}/docs"
          echo "public url: https://pull-requests.pmd-code.org/pr-${PR_NUMBER}/docs"
      - name: Add commit status (Documentation)
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/pmd/pmd/statuses/${PR_SHA} \
            -f "state=success" -f "target_url=https://pull-requests.pmd-code.org/pr-${PR_NUMBER}/docs" \
            -f "description=PMD Documentation Preview" -f "context=Published Results / Documentation"
      - name: Download pmd-regression-tester (optional)
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          mkdir pmd-regression-tester
          cd pmd-regression-tester
          if gh run download "${RUN_ID}" --repo pmd/pmd --name pmd-regression-tester; then
            echo "HAS_REGRESSION_REPORT=1" >> "$GITHUB_ENV"
          fi
      - name: Upload regression report to s3://pmd-pull-requests
        if: ${{ env.HAS_REGRESSION_REPORT == 1 }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_PMD_PULL_REQUESTS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_PMD_PULL_REQUESTS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
        run: |
          tar xfzv pmd-regression-tester/pr-${PR_NUMBER}-*.tar.gz
          aws s3 sync diff1 "s3://pmd-pull-requests/pr-${PR_NUMBER}/regression"
          echo "public url: https://pull-requests.pmd-code.org/pr-${PR_NUMBER}/regression"
      - name: Add commit status (Regression Tester)
        if: ${{ env.HAS_REGRESSION_REPORT == 1 }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/pmd/pmd/statuses/${PR_SHA} \
            -f "state=success" -f "target_url=https://pull-requests.pmd-code.org/pr-${PR_NUMBER}/regression" \
            -f "description=PMD Regression Tester Report" -f "context=Published Results / Regression Tester"
      - name: Add Check Status (Documentation)
        run: |
          timestamp="$(date -uIs)"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/pmd/pmd/check-runs \
            -f "name=Documentation" -f "head_sha=${PR_SHA}" -f "status=completed" \
            -f "started_at=${timestamp}" -f "conclusion=success" -f "completed_at=${timestamp}" \
            -f "output[title]=Documentation Preview" -f "output[summary]=[Documentation Preview](https://pull-requests.pmd-code.org/pr-${PR_NUMBER}/docs)"
      - name: Add Check Status (Regression Tester)
        if: ${{ env.HAS_REGRESSION_REPORT == 1 }}
        run: |
          timestamp="$(date -uIs)"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/pmd/pmd/check-runs \
            -f "name=Regression Tester" -f "head_sha=${PR_SHA}" -f "status=completed" \
            -f "started_at=${timestamp}" -f "conclusion=success" -f "completed_at=${timestamp}" \
            -f "output[title]=Regression Tester Report" -f "output[summary]=[Regression Tester Report](https://pull-requests.pmd-code.org/pr-${PR_NUMBER}/regression)"
